### PR TITLE
Adds Grunt Jekyll plugin, updates deployment

### PR DESCRIPTION
**Pull request by kennethormandy**
Hey!

I updated the Style & Class site to use the Grunt Jekyll plugin and [Surge](https://surge.sh) if you’re interested.
- After running `npm install`, running `grunt deploy` will now prompt you to sign up and deploy to `styleandclass.surge.sh` (you won’t have to login next time)
- You can also update the Gruntfile to [use the custom styleandclass.ca domain](http://surge.sh/help/adding-a-custom-domain) instead if you like how that goes

Surge also supports collaborators, so then you can add organizers:

```
npm install -g surge
surge ./_site styleandclass.ca --add example@mobify.com
```

…where example@mobify.com is replaced with the new organizer’s email address. This will re-deploy the site and send an an email giving the new organizer permission to deploy the project too. (I can work on adding this to the Grunt plugin directly if you’re interested, right now you still have to do it through the global Surge module.)

Let me know if this is helpful at all, I’d love to get your feedback.

### CODE REVIEW

**Comment by kpeatt** [comment]
Whoa, awesome @kennethormandy! Thanks!

**Comment by kennethormandy** [comment]
Rebased to the best of my ability :octocat:

**Comment by mezzoblue** [comment]
Thanks Kenneth! Long time coming, but I finally got around to testing and this'll be a huge help for us.

**Comment by kennethormandy** [comment]
Awesome! Glad it was helpful. If you want, we also support [Travis CI](https://surge.sh/help/integrating-with-travis-ci), [Codeship](https://surge.sh/help/integrating-with-codeship), etc. now so you can have the site automatically build and deploy when the `master` branch is updated (or however you like to do it).

**Pull request merged**
