### PR TITLE
Adding in Grunt to the project with CssMin and AutoPrefixer

### PR DESCRIPTION
**Pull request by stevemynett**
Soo.... about this grunt thing. 

You'll either accept this quickly because there _aren't_ a ton of changes, or (flipdesk) and wonder why you ever had a beer with me. 

I moved everything from the repo root into a "root" folder. This lets me have a project root with config and grunt files independent of the project. Otherwise things like the `Gruntfile.js` and `node_modules` would compile into the jekyll project which is even weirder than this. 

I'm open to better ways if this is heavy handed. 

I only changed the contents of four files: 
- .gitignore
- package.json
- Gruntfile.js
- /root/_site/css/main.css (only changed with minification and autoprefixing) 

In the mean time these two commands should do stuff: 
- `grunt cssmin` - minify CSS (savin 6k -- #webperf #amirite?) 
- `grunt autoprefixer` auto prefix the same CSS file adding back in 2k of stuff. But we work in IE8!

Obviously these configs can be changed.

### CODE REVIEW

**Comment by stevemynett** [comment]
Also the readme.md would have to change to reflect folder structure change. I'll update that in a future commit if this is accepted.

**Comment by mezzoblue** [comment]
7000488483_cc3339995a_b

**Comment by mezzoblue** [comment]
I'll accept this as a necessary evil.

**Comment by mezzoblue** [comment]
Er uh where'd ya put Gruntfile.js?

For that matter, where's /root/?

**Pull request merged**
